
name: UpdateIptv

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

#permissions:
#  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run iptv
      run: python ${{ github.workspace }}/UpdateIptv.py

    - name: 提交更改
      run: |
        git config --local user.email "767488371@qq.com"
        git config --local user.name "dushan555"
        git add .
        git commit iptv.txt -m "Update Iptv file"
        # git commit *.txt -m "Add generated file"
        # git commit *.m3u -m "Add generated file"
        #git pull --rebase
        git push -f
